#!/bin/bash -x

env | grep DOCKER
if [ -x /usr/bin/docker.io ]
then
  sudo /bin/docker.io "$@"
else
  echo "Error! /usr/bin/docker.io is not executable or inexistent. Did you mounted your host docker binary to /usr/bin/docker.io ?"
  exit 1
fi
